[package]
name = "rusty-raytracing-weekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.20.2"
rand = "*"
pixels = "*"
winit = "0.26"
winit_input_helper = "0.11"
log = "0.4.0"
env_logger = "0.8.4"
itertools = "*"